import type { APIRoute } from "astro";
import { db } from "@db/index";
import { offices } from "@db/schema";
import { generateCsv } from "@lib/csv";

export const GET: APIRoute = async () => {
  try {
    const data = await db.select().from(offices);

    const headers = [
      "ID",
      "Código",
      "Nombre",
      "Tipo",
      "Cód. Provincia",
      "Dirección",
      "Latitud",
      "Longitud",
      "Correo",
      "Notas",
      "Calle",
      "Número",
      "Localidad",
      "Partido",
      "Zona",
      "Tipo Oficina",
      "Clase Categoría",
      "Rubro",
      "NIS Padre",
      "Teléfono",
      "Gerente",
      "ID Región",
      "En Red",
      "Admisión PaqAr",
      "Entrega PaqAr",
      "Payroll",
      "Exento Impuestos",
      "División",
      "Compañía",
      "Almacén",
      "Centro de Beneficio",
      "CCT Oficina Admin",
      "CC Comercial",
      "CC Comercial Corp",
      "CC Electoral",
      "CC Gestión de Red",
      "CC Operaciones",
      "CC Operativo",
      "CC RRHH",
      "CC Seguridad",
      "CC Admin",
      "CC Admisión",
      "CC CTP",
      "CC CTT",
      "CC Transporte",
      "CC Logística",
      "POS Auto-Auto",
      "POS Cta. Corriente",
      "POS Manual",
      "POS Manual-Auto",
      "POS Planta MG",
      "POS Virtual",
      "POS Auto-Auto 2",
      "POS Terminal SAP",
      "Texto de Búsqueda",
    ];

    const rows = data.map((office) => [
      office.id,
      office.code,
      office.name,
      office.type,
      office.provinceCode,
      office.address,
      office.lat,
      office.lng,
      office.email,
      office.notes,
      office.street,
      office.number,
      office.locality,
      office.county,
      office.zone,
      office.officeType,
      office.categoryClass,
      office.rubric,
      office.parentNis,
      office.phone,
      office.manager,
      office.regionId,
      office.enRed ? "Sí" : "No",
      office.paqarAdmision ? "Sí" : "No",
      office.paqarEntrega ? "Sí" : "No",
      office.payroll ? "Sí" : "No",
      office.taxExempt ? "Sí" : "No",
      office.division,
      office.company,
      office.warehouse,
      office.profitCenter,
      office.cctAdminOffice,
      office.ccCommercial,
      office.ccCommercialCorp,
      office.ccElectoral,
      office.ccNetworkMgmt,
      office.ccOperations,
      office.ccOperational,
      office.ccHr,
      office.ccSecurity,
      office.ccAdmin,
      office.ccAdmission,
      office.ccCtp,
      office.ccCtt,
      office.ccTransport,
      office.ccLogistics,
      office.posAutoAuto,
      office.posCurrentAccount,
      office.posManual,
      office.posManualAuto,
      office.posPlantaMg,
      office.posVirtual,
      office.posAutoAuto2,
      office.posSapTerminal,
      office.searchableText,
    ]);

    const csvStr = generateCsv(headers, rows);
    const dateStr = new Date().toISOString().split('T')[0];

    return new Response(csvStr, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="oficinas_${dateStr}.csv"`,
        "Cache-Control": "public, max-age=3600",
      },
    });
  } catch (error) {
    console.error("Error generating offices CSV:", error);
    return new Response("Error al generar el archivo CSV.", { status: 500 });
  }
};
